"use strict";

const priyaProperties = [
  {
    id: "priya-1",
    title: "Prestige Sunrise Park – Premium 3BHK",
    type: "Apartment",
    status: "Ready to Move",
    price: "₹1.25 Cr",
    priceValue: 12500000,
    location: "Whitefield, Bangalore",
    city: "Bangalore",
    area: "1,650 sq.ft.",
    beds: 3,
    baths: 2,
    image: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&q=80",
    description: "Luxury 3BHK in a gated community with world-class amenities, lush greenery, and seamless connectivity to IT hubs.",
    featured: true,
  },
  {
    id: "priya-2",
    title: "DLF Cyber City – Studio Apartment",
    type: "Apartment",
    status: "Fast Selling",
    price: "₹55 Lakhs",
    priceValue: 5500000,
    location: "Cyber City, Hyderabad",
    city: "Hyderabad",
    area: "620 sq.ft.",
    beds: 1,
    baths: 1,
    image: "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800&q=80",
    description: "Smart studio apartment ideal for working professionals. Steps from Hyderabad's top IT corridors.",
    featured: true,
  },
  {
    id: "priya-3",
    title: "Maple Heights – 2BHK Apartment",
    type: "Apartment",
    status: "New Launch",
    price: "₹82 Lakhs",
    priceValue: 8200000,
    location: "Hinjewadi, Pune",
    city: "Pune",
    area: "1,100 sq.ft.",
    beds: 2,
    baths: 2,
    image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=80",
    description: "Elegant 2BHK with modern interiors, close to Pune's IT hub and expressway access.",
    featured: true,
  },
  {
    id: "priya-4",
    title: "Premium Villa – Electronic City",
    type: "Villa",
    status: "Premium Amenities",
    price: "₹3.2 Cr",
    priceValue: 32000000,
    location: "Electronic City, Bangalore",
    city: "Bangalore",
    area: "3,200 sq.ft.",
    beds: 4,
    baths: 4,
    image: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&q=80",
    description: "Stunning 4BHK villa with private pool, home automation, and landscaped gardens in Electronic City.",
    featured: true,
  },
  {
    id: "priya-5",
    title: "Skyline Residency – Row House",
    type: "Row House",
    status: "Ready to Move",
    price: "₹1.8 Cr",
    priceValue: 18000000,
    location: "Kondapur, Hyderabad",
    city: "Hyderabad",
    area: "2,100 sq.ft.",
    beds: 3,
    baths: 3,
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80",
    description: "Spacious row house in a gated community with beautiful interiors and private garden space.",
    featured: false,
  },
  {
    id: "priya-6",
    title: "Tech Park Commercial Plot",
    type: "Commercial",
    status: "New Launch",
    price: "₹4.5 Cr",
    priceValue: 45000000,
    location: "Aundh, Pune",
    city: "Pune",
    area: "5,000 sq.ft.",
    beds: 0,
    baths: 0,
    image: "https://images.unsplash.com/photo-1486325212027-8081e485255e?w=800&q=80",
    description: "Prime commercial land in Pune's fastest growing tech corridor. Ideal for offices, showrooms, or IT parks.",
    featured: false,
  },
];

const priyaAgents = [
  {
    id: "pa-1",
    name: "Ravi Krishnamurthy",
    role: "Senior Sales Executive",
    experience: "8 Years",
    specialty: "Luxury Apartments",
    areas: "Bangalore, Whitefield",
    phone: "+91 98765 43210",
    email: "ravi@priyaestates.in",
    image: "",
  },
  {
    id: "pa-2",
    name: "Sneha Patel",
    role: "Property Consultant",
    experience: "5 Years",
    specialty: "Commercial Properties",
    areas: "Pune, Hinjewadi",
    phone: "+91 98765 43211",
    email: "sneha@priyaestates.in",
    image: "",
  },
];

const priyaFounder = {
  name: "Priya Suresh",
  title: "Founder & Managing Director",
  bio: "Priya Suresh founded Priya Estates with a vision to make quality real estate accessible across India's top metro cities. With over 15 years in the industry, she has built a reputation for trust, transparency, and delivering exceptional value to clients in Bangalore, Hyderabad, and Pune.",
  image: "",
  phone: "+91 98765 43210",
  email: "priya@priyaestates.in",
  linkedIn: "",
};

const priyaContacts = [
  { id: "pc-1", label: "Main Office", number: "+91 98765 43210", type: "Office" },
  { id: "pc-2", label: "WhatsApp", number: "+91 98765 43210", type: "WhatsApp" },
  { id: "pc-3", label: "Sales Team", number: "+91 98765 43211", type: "Sales" },
];

const priyaReviews = [
  { id: "pr-1", name: "Arun Mehta", purchase: "3BHK Apartment, Whitefield", text: "Priya Estates made our home buying journey absolutely smooth. Professional, transparent and genuinely caring.", rating: 5 },
  { id: "pr-2", name: "Divya Nair", purchase: "Studio, Hyderabad", text: "Found my perfect studio in just one visit. The team understood exactly what I needed.", rating: 5 },
  { id: "pr-3", name: "Ramesh Babu", purchase: "Villa, Electronic City", text: "Premium service for a premium property. Highly recommended for luxury seekers.", rating: 4 },
];

const prithviProperties = [
  {
    id: "prithvi-1",
    title: "DTCP Approved Residential Plot – T.Vadipatti",
    type: "Residential Plots",
    status: "Available",
    price: "₹12 Lakhs",
    priceValue: 1200000,
    bookingAmount: "₹50,000",
    location: "T.Vadipatti, Madurai",
    city: "Madurai",
    area: "2,400 Sq.ft. (40×60)",
    ownership: "Clear Title",
    saleType: "Direct Sale",
    project: "Green Valley Layout",
    description: "DTCP approved residential plot in a lush gated layout with tree-lined roads, underground drainage, and clear titles. Ideal for building your dream home or investment.\n\nKey Features:\n• DTCP Approved Layout\n• Clear Title Deed\n• Underground drainage\n• Black top roads\n• 24/7 water supply",
    landmarks: ["School", "Hospital", "Bank", "Bus Stop"],
    nearbyPlaces: ["T.Vadipatti town center – 2 km", "Madurai city center – 22 km", "Schools – 1 km"],
    tags: ["DTCP Approved", "Clear Title", "Gated Layout", "40×60", "Residential"],
    images: ["https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=1200&q=80"],
    youtubeLinks: [],
    featured: true,
    lat: 9.9898,
    lng: 78.0748,
  },
  {
    id: "prithvi-2",
    title: "Agricultural Land – Alanganallur",
    type: "Farm / Agricultural Land",
    status: "Available",
    price: "₹8 Lakhs/Acre",
    priceValue: 800000,
    bookingAmount: "₹25,000",
    location: "Alanganallur, Madurai",
    city: "Madurai",
    area: "3.5 Acres",
    ownership: "Clear Title",
    saleType: "Direct Sale",
    project: "",
    description: "Fertile agricultural land with year-round water source (bore well). Suitable for organic farming, mango/coconut cultivation, and eco-resort development.\n\n• Patta in owner's name\n• Bore well with motor pump\n• Electricity connection available\n• Road access on all sides",
    landmarks: ["School", "Highway", "Bank"],
    nearbyPlaces: ["Alanganallur town – 3 km", "Jallikattu grounds – 1 km", "Madurai – 25 km"],
    tags: ["Agricultural", "Bore Well", "Clear Patta", "Road Access", "3.5 Acres"],
    images: ["https://images.unsplash.com/photo-1416331108676-a22ccb276e35?w=1200&q=80"],
    youtubeLinks: [],
    featured: true,
    lat: 9.9765,
    lng: 78.2548,
  },
  {
    id: "prithvi-3",
    title: "Commercial Land – Bypass Road",
    type: "Commercial Land",
    status: "Available",
    price: "₹2.8 Cr",
    priceValue: 28000000,
    bookingAmount: "₹5,00,000",
    location: "Bypass Road, Madurai",
    city: "Madurai",
    area: "10,000 Sq.ft.",
    ownership: "Clear Title",
    saleType: "Direct Sale",
    project: "",
    description: "Premium commercial land on Madurai Bypass Road – the city's fastest-growing commercial corridor. Ideal for showroom, hotel, hospital, or mixed-use development.\n\n• 80-foot road frontage\n• High visibility location\n• All approvals facilitated\n• Clear legal title",
    landmarks: ["Hospital", "Shopping Mall", "Bank", "Highway", "Bus Stop"],
    nearbyPlaces: ["Madurai Bypass – direct frontage", "City center – 10 km", "Airport – 8 km"],
    tags: ["Commercial", "Bypass Road", "High Visibility", "80ft Frontage", "Approved"],
    images: ["https://images.unsplash.com/photo-1486325212027-8081e485255e?w=1200&q=80"],
    youtubeLinks: [],
    featured: true,
    lat: 9.9485,
    lng: 78.1448,
  },
  {
    id: "prithvi-4",
    title: "Independent House – Anna Nagar, Madurai",
    type: "Independent House",
    status: "Available",
    price: "₹85 Lakhs",
    priceValue: 8500000,
    bookingAmount: "₹2,00,000",
    location: "Anna Nagar, Madurai",
    city: "Madurai",
    area: "1,800 Sq.ft.",
    ownership: "Clear Title",
    saleType: "Direct Sale",
    project: "",
    description: "Well-maintained independent house in the heart of Anna Nagar. G+1 structure with 4 bedrooms, hall, kitchen, and covered parking. Vastu-compliant design.\n\n• 4 bedrooms, 3 bathrooms\n• G+1 structure on 1,200 sq.ft. plot\n• Covered car parking\n• Solar water heater\n• Bore well + metro water",
    landmarks: ["School", "Hospital", "Shopping Mall", "Bank", "Bus Stop"],
    nearbyPlaces: ["Anna Nagar market – 0.5 km", "Schools – walking distance", "Madurai junction – 5 km"],
    tags: ["Independent House", "G+1", "Anna Nagar", "Vastu Compliant", "4 BHK"],
    images: ["https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=1200&q=80"],
    youtubeLinks: [],
    featured: true,
    lat: 9.9374,
    lng: 78.1215,
  },
  {
    id: "prithvi-5",
    title: "Residential Flat – Mattuthavani",
    type: "Flats / Apartments",
    status: "Available",
    price: "₹48 Lakhs",
    priceValue: 4800000,
    bookingAmount: "₹1,00,000",
    location: "Mattuthavani, Madurai",
    city: "Madurai",
    area: "1,050 Sq.ft.",
    ownership: "Builder Floor",
    saleType: "Direct Sale",
    project: "GreenVille Residency",
    description: "Modern 2BHK flat in the thriving Mattuthavani area. TNRERA registered project with premium finishes and all amenities.\n\n• 2 BHK – 1,050 sq.ft.\n• East-facing\n• TNRERA approved\n• Lift, car parking, generator backup\n• Gym and rooftop terrace",
    landmarks: ["Bus Stop", "Hospital", "Bank", "Airport"],
    nearbyPlaces: ["Mattuthavani bus terminus – 5 min", "Airport – 15 min", "Banks – walking distance"],
    tags: ["2 BHK", "TNRERA Approved", "Lift", "Parking", "East Facing"],
    images: ["https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=1200&q=80"],
    youtubeLinks: [],
    featured: true,
    lat: 9.9220,
    lng: 78.1380,
  },
];

const prithviFounder = {
  name: "Subbulakshmi Saravanan",
  title: "Founder & CEO",
  experience: "12+ Years",
  address: "No. 5, Kamarajar Salai, Anna Nagar, Madurai – 625 020",
  phone: "+91 98421 00000",
  email: "subbulakshmi@prithvirealestate.in",
  teamSize: "12",
  bio: "Subbulakshmi Saravanan established Prithvi Real Estate in 2012 with a commitment to eco-friendly and sustainable property development in Madurai and surrounding Tamil Nadu districts. With a background in land surveying and legal consultation, she brings unmatched expertise in DTCP approvals, agricultural land deals, and rural-to-urban plot development.",
  image: "",
};

const prithviAgents = [
  { id: "ag-1", name: "Karthik Murugan", role: "Senior Property Advisor", phone: "+91 98421 00001", email: "karthik@prithvirealestate.in", bio: "Specialist in agricultural and residential land across Madurai district.", image: "" },
  { id: "ag-2", name: "Radha Selvam", role: "Legal & Documentation Head", phone: "+91 98421 00002", email: "radha@prithvirealestate.in", bio: "Expert in DTCP approvals, patta transfers, and property registration.", image: "" },
];

const prithviContacts = [
  { id: "pc-1", label: "Main Office", number: "+91 98421 00000", type: "Office" },
  { id: "pc-2", label: "WhatsApp", number: "+91 98421 00000", type: "WhatsApp" },
  { id: "pc-3", label: "Sales", number: "+91 98421 00001", type: "Sales" },
];

const prithviSiteInfo = {
  agencyName: "Prithvi Real Estate",
  tagline: "Growing Roots in Tamil Nadu Soil",
  about: "Prithvi Real Estate is a Madurai-based property consultancy specializing in DTCP approved layouts, agricultural land, and residential properties across Tamil Nadu. We connect buyers with verified, clear-title properties and provide full legal support from purchase to registration.",
  address: "No. 5, Kamarajar Salai, Anna Nagar, Madurai – 625 020",
  phone: "+91 98421 00000",
  email: "info@prithvirealestate.in",
  whatsapp: "+91 98421 00000",
  established: "2012",
  areasOfOperation: ["Madurai", "Sivaganga", "Dindigul", "Virudhunagar", "Theni", "Ramanathapuram"],
  propertyTypes: ["Commercial Land", "Residential Plots", "Flats / Apartments", "Independent House", "Farm / Agricultural Land", "Industrial Land"],
};

const bhimaProperties = [
  {
    id: "bhima-1",
    title: "Blu Bell Premium Apartments – 3 BHK",
    type: "Flats / Apartments",
    status: "Booking Open",
    price: "₹75 Lakhs",
    priceValue: 7500000,
    location: "Bypass Road, Madurai",
    city: "Madurai",
    area: "1,450 Sq.ft.",
    bedrooms: "3",
    bathrooms: "3",
    facing: "East",
    floor: "3rd – 8th Floor",
    project: "Blu Bell Apartments",
    description: "Premium 3 BHK apartments in the flagship Blu Bell Apartments project by Bhima Homes. Located on the Bypass Road, these homes offer the perfect blend of modern architecture and lifestyle comfort.\n\nKey Highlights:\n• Spacious 1,450 sq.ft. layouts with premium finishes\n• Swimming pool and toddler pool\n• 24/7 security with CCTV\n• Indoor gym with panoramic views\n• Terrace party hall\n• Children's play area and landscaped gardens\n• TNRERA approved project",
    landmarks: ["School", "Hospital", "Shopping Mall", "Bank", "Bus Stop", "Highway"],
    nearbyPlaces: ["Bypass Road – direct access", "Major shopping malls – 5 min", "Schools and colleges – walking distance", "Hospitals – 10 min"],
    amenities: ["Swimming Pool", "Gym", "24/7 Security", "CCTV", "Terrace Party Hall", "Children's Play Area", "Landscaped Gardens", "Power Backup"],
    tags: ["TNRERA Approved", "Premium", "Gated Community", "Swimming Pool", "3 BHK", "Ready to Move"],
    images: ["https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=1200&q=80", "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=1200&q=80", "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=1200&q=80"],
    youtubeLinks: [],
    featured: true,
  },
  {
    id: "bhima-2",
    title: "Blu Bell Apartments – 2 BHK Studio",
    type: "Studio Apartments",
    status: "Booking Open",
    price: "₹52 Lakhs",
    priceValue: 5200000,
    location: "Bypass Road, Madurai",
    city: "Madurai",
    area: "980 Sq.ft.",
    bedrooms: "2",
    bathrooms: "2",
    facing: "West",
    floor: "1st – 5th Floor",
    project: "Blu Bell Apartments",
    description: "Thoughtfully designed 2 BHK studio apartments in the Blu Bell project — ideal for working professionals and young families.\n\n• Well-planned 980 sq.ft. floor plan\n• Modern kitchen with granite countertops\n• Vitrified tile flooring throughout\n• Premium bathroom fittings\n• Dedicated parking for all units\n• Vastu-compliant design",
    landmarks: ["School", "Hospital", "Shopping Mall", "Bank", "Bus Stop"],
    nearbyPlaces: ["Bypass Road – 2 min", "City center – 15 min", "Railway station – 20 min"],
    amenities: ["Swimming Pool", "Gym", "24/7 Security", "Parking", "Power Backup", "CCTV"],
    tags: ["2 BHK", "Studio", "Affordable", "Vastu Compliant", "Booking Open"],
    images: ["https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=1200&q=80", "https://images.unsplash.com/photo-1484154218962-a197022b5858?w=1200&q=80"],
    youtubeLinks: [],
    featured: true,
  },
  {
    id: "bhima-3",
    title: "4 BHK Independent Villa – Anna Nagar",
    type: "Independent House",
    status: "Available",
    price: "₹1.8 Cr",
    priceValue: 18000000,
    location: "Anna Nagar, Madurai",
    city: "Madurai",
    area: "2,800 Sq.ft.",
    bedrooms: "4",
    bathrooms: "4",
    facing: "North",
    floor: "G+2",
    project: "",
    description: "Elegant G+2 independent villa in Anna Nagar, one of Madurai's most prestigious localities.\n\n• 2,800 sq.ft. built-up area on 2,400 sq.ft. plot\n• Italian marble flooring in living areas\n• Modular kitchen with chimney\n• Terrace garden with city views\n• 2-car garage\n• Solar panels and rainwater harvesting",
    landmarks: ["School", "Hospital", "Shopping Mall", "Bank", "Park"],
    nearbyPlaces: ["Anna Nagar market – 5 min", "Top schools – walking distance", "Hospitals – 10 min"],
    amenities: ["Terrace Garden", "2-Car Garage", "Solar Panels", "Rainwater Harvesting", "CCTV"],
    tags: ["Independent House", "4 BHK", "Anna Nagar", "Premium Villa", "G+2", "Vastu Compliant"],
    images: ["https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=1200&q=80", "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200&q=80"],
    youtubeLinks: [],
    featured: true,
  },
  {
    id: "bhima-4",
    title: "Commercial Shop Space – Avaniyapuram",
    type: "Commercial Shops",
    status: "Available",
    price: "₹45 Lakhs",
    priceValue: 4500000,
    location: "Avaniyapuram Main Road, Madurai",
    city: "Madurai",
    area: "650 Sq.ft.",
    bedrooms: "",
    bathrooms: "1",
    facing: "East",
    floor: "Ground Floor",
    project: "",
    description: "Prime ground-floor commercial shop on Avaniyapuram Main Road.\n\n• 650 sq.ft. with 22-foot frontage\n• 24-hour power supply with DG backup\n• Ample parking for customers\n• High footfall zone",
    landmarks: ["Bus Stop", "Bank", "Shopping Mall", "Highway"],
    nearbyPlaces: ["Avaniyapuram bus stand – 2 min", "Major banks – adjacent"],
    amenities: ["Power Backup", "24/7 Access", "CCTV"],
    tags: ["Commercial", "Ground Floor", "High Footfall", "Main Road", "22ft Frontage"],
    images: ["https://images.unsplash.com/photo-1486325212027-8081e485255e?w=1200&q=80"],
    youtubeLinks: [],
    featured: true,
  },
  {
    id: "bhima-5",
    title: "Residential Plot – Airport Road",
    type: "Residential Plots",
    status: "Available",
    price: "₹38 Lakhs",
    priceValue: 3800000,
    location: "Airport Road, Madurai",
    city: "Madurai",
    area: "2,400 Sq.ft. (40×60)",
    bedrooms: "",
    bathrooms: "",
    facing: "North",
    floor: "",
    project: "DTCP Approved Layout",
    description: "DTCP approved residential plot in a premium gated layout on Airport Road.\n\n• 40×60 North-facing plot\n• Black top tar roads\n• Underground drainage and water connection\n• 24/7 security\n• Street lighting throughout",
    landmarks: ["Airport", "Hospital", "School", "Highway", "Bank"],
    nearbyPlaces: ["Madurai International Airport – 5 min", "IT Park – 10 min", "City center – 20 min"],
    amenities: ["24/7 Security", "Underground Drainage", "Street Lighting", "Black Top Roads"],
    tags: ["DTCP Approved", "Residential", "Airport Road", "North Facing", "Gated Layout", "40×60"],
    images: ["https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=1200&q=80", "https://images.unsplash.com/photo-1416331108676-a22ccb276e35?w=1200&q=80"],
    youtubeLinks: [],
    featured: true,
  },
  {
    id: "bhima-6",
    title: "Office Space – Mattuthavani Business Hub",
    type: "Office Space",
    status: "Available",
    price: "₹1.2 Cr",
    priceValue: 12000000,
    location: "Mattuthavani, Madurai",
    city: "Madurai",
    area: "1,800 Sq.ft.",
    bedrooms: "",
    bathrooms: "2",
    facing: "South",
    floor: "4th Floor",
    project: "Business Hub Tower",
    description: "Modern, ready-to-occupy office space in the thriving Mattuthavani business district.\n\n• Open-plan layout with modular partitions\n• High-speed fiber optic internet ready\n• 2 dedicated parking slots\n• Centralized AC\n• Conference room with projector",
    landmarks: ["Bus Stop", "Bank", "Hospital", "Airport"],
    nearbyPlaces: ["Mattuthavani bus terminus – 5 min", "Madurai Airport – 15 min"],
    amenities: ["Centralized AC", "Fiber Internet", "Conference Room", "Parking", "Power Backup", "CCTV"],
    tags: ["Office Space", "Premium", "Mattuthavani", "Ready to Move", "IT Ready"],
    images: ["https://images.unsplash.com/photo-1497366216548-37526070297c?w=1200&q=80", "https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=1200&q=80"],
    youtubeLinks: [],
    featured: false,
  },
];

const bhimaFounder = {
  name: "Pradeep Jaikumar",
  title: "Founder & Managing Director",
  experience: "16+ Years of Experience",
  address: "52A, 120 feet Surveyor Colony Road, Mattuthavani, Madurai",
  phone: "+91 82303 00000",
  email: "info@bhimahomes.in",
  bio: "Pradeep Jaikumar founded Bhima Homes and Properties in 2010 with a vision to bring professional-grade property consulting to Madurai. Leading a team of architects, civil engineers, and legal experts, he has built the company into a trusted name in the region. From technical verification to legal opinions and registration, Bhima Homes offers end-to-end property services.",
  image: "",
};

const bhimaServices = [
  { id: "bs-1", title: "Architecture", description: "Professional architectural design and planning for residential and commercial spaces.", icon: "🏛️" },
  { id: "bs-2", title: "Landscape Design", description: "Beautiful, functional landscape design that enhances your property value.", icon: "🌿" },
  { id: "bs-3", title: "Exterior Design", description: "Striking exterior finishes that give your property lasting curb appeal.", icon: "🏠" },
  { id: "bs-4", title: "Structural Planning", description: "Safe, efficient structural engineering for all building types.", icon: "📐" },
  { id: "bs-5", title: "Interior & Furniture Design", description: "Custom interior design solutions tailored to your lifestyle and taste.", icon: "🛋️" },
  { id: "bs-6", title: "Legal & Registration", description: "Expert legal opinion, title verification, and registration assistance.", icon: "⚖️" },
  { id: "bs-7", title: "Vaastu Consulting", description: "Traditional Vaastu principles integrated into modern property planning.", icon: "🔱" },
  { id: "bs-8", title: "Property Consulting", description: "End-to-end advisory for buying, selling and investing in property.", icon: "📊" },
];

const bhimaContacts = [
  { id: "bc-1", label: "Main Office", number: "+91 82303 00000", type: "Office" },
  { id: "bc-2", label: "WhatsApp", number: "+91 82303 00000", type: "WhatsApp" },
  { id: "bc-3", label: "Sales", number: "+91 82303 00001", type: "Sales" },
];

const bhimaSiteInfo = {
  agencyName: "Bhima Homes and Properties",
  tagline: "Building Foundations That Last",
  about: "Bhima Homes and Properties is a property development company led by professionals including Architects, Civil Engineers, and elite real estate consultants. Since 2010, we have been dealing in all types of properties based on buyer requirements. We also serve post-property buying needs — technical verification, legal opinions, and registration/approval processes.",
  address: "52A, 120 feet Surveyor Colony Road, Mattuthavani, Madurai",
  phone: "+91 82303 00000",
  email: "info@bhimahomes.in",
  whatsapp: "+91 82303 00000",
  established: "2010",
  areasOfOperation: ["Agrini, Madurai", "Airport Road, Madurai", "Alagar Kovil, Madurai", "Alagappan Nagar, Madurai", "Alanganallur, Madurai", "Anna Nagar, Madurai", "Avaniyapuram, Madurai", "Bypass Road, Madurai", "Doak Nagar, Madurai", "Duraisamy Nagar, Madurai", "Mattuthavani, Madurai", "Coimbatore"],
  propertyTypes: ["Flats / Apartments", "Independent House", "Builder Floor", "Farm House", "Commercial Shops", "Showroom", "Office Space", "Residential Plots", "Farm / Agricultural Land", "Commercial Plots", "Penthouse", "Studio Apartments", "Warehouse / Godown", "Hotel & Restaurant"],
};

module.exports = {
  priyaProperties, priyaAgents, priyaFounder, priyaContacts, priyaReviews,
  prithviProperties, prithviFounder, prithviAgents, prithviContacts, prithviSiteInfo,
  bhimaProperties, bhimaFounder, bhimaServices, bhimaContacts, bhimaSiteInfo,
};
